import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Header, HTTPException, Query, UploadFile
from fastapi.responses import StreamingResponse

from app.config import settings
from app.core.csv_parser import parse_csv
from app.core.pipeline import process_csv
from app.models.job import JobStatus, PipelineJob
from app.services import supabase_service
from app.utils.exceptions import CSVValidationError
from app.utils.logger import get_logger
from app.utils.sse import format_sse

router = APIRouter()
logger = get_logger(__name__)

# In-memory job store (suitable for POC; replace with Redis for production)
_jobs: dict[str, PipelineJob] = {}


@router.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@router.get("/config")
async def get_config() -> dict:
    """Return public frontend config (Supabase URL + anon key for browser auth)."""
    return {
        "supabase_url": settings.supabase_url,
        "supabase_anon_key": settings.supabase_anon_key,
    }


@router.get("/history")
async def get_history(user_id: str = Query(default="")) -> list[dict]:
    """Return all content assets previously generated by this user."""
    if not user_id:
        return []
    return await supabase_service.get_user_history(user_id)


@router.post("/process")
async def process(
    file: UploadFile,
    x_user_id: str = Header(default=""),
) -> StreamingResponse:
    job_id = str(uuid.uuid4())
    user_id = x_user_id or ""
    logger.info("process_started", job_id=job_id, filename=file.filename, user_id=user_id or "anonymous")

    try:
        rows = await parse_csv(file)
    except CSVValidationError as exc:
        logger.warning("csv_validation_failed", job_id=job_id, error=str(exc))
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    job = PipelineJob(
        id=job_id,
        status=JobStatus.processing,
        created_at=datetime.now(timezone.utc),
        rows_total=len(rows),
        rows_done=0,
    )
    _jobs[job_id] = job

    async def event_stream():
        yield format_sse("job_started", {"job_id": job_id, "rows_total": len(rows)})
        async for event_name, event_data in process_csv(rows, job_id, user_id=user_id):
            if event_name == "row_done":
                job.rows_done += 1
            yield format_sse(event_name, event_data)
        job.status = JobStatus.complete
        await supabase_service.complete_job(job_id, job.rows_done)
        yield format_sse("job_complete", {"job_id": job_id, "rows_done": job.rows_done})
        logger.info("process_complete", job_id=job_id, rows_done=job.rows_done)

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "X-Accel-Buffering": "no",
        },
    )


@router.delete("/assets/{product_id}")
async def delete_asset(
    product_id: str,
    x_user_id: str = Header(default=""),
) -> dict:
    """Delete a single content asset and its associated storage objects."""
    await supabase_service.delete_asset(product_id, x_user_id)
    return {"deleted": product_id}


@router.get("/status/{job_id}")
async def job_status(job_id: str) -> PipelineJob:
    job = _jobs.get(job_id)
    if not job:
        raise HTTPException(status_code=404, detail=f"Job {job_id!r} not found")
    return job
